import { ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder } from 'discord.js';
import { evaluateMathExpression } from '../../utils/safeMathParser.js';
const SUFFIXES={k:1e3,m:1e6,b:1e9,t:1e12};
function normalize(e){return String(e).replace(/,/g,'').replace(/×/g,'*').replace(/÷/g,'/').replace(/([0-9]+(?:\.[0-9]+)?)([KMBT])\b/gi,(_,n,s)=>`${Number(n)*SUFFIXES[s.toLowerCase()]}`)}
function calc(e){const n=normalize(e);if(!/^[0-9+\-*/%^().\s]+$/.test(n))throw new Error('Use numbers with K, M, B, T and +, -, ×, ÷.');return evaluateMathExpression(n)}
function fmt(v){for(const [s,u] of [[1e12,'T'],[1e9,'B'],[1e6,'M'],[1e3,'K']])if(Math.abs(v)>=s)return `${(v/s).toFixed(3).replace(/\.?(0+)$/,'')}${u}`;return Number(v.toFixed(6)).toLocaleString('en-US')}
function rows(){return [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('calc_plus').setLabel('+').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('calc_minus').setLabel('−').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('calc_multiply').setLabel('×').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('calc_divide').setLabel('÷').setStyle(ButtonStyle.Secondary)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('calc_k').setLabel('K').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('calc_m').setLabel('M').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('calc_b').setLabel('B').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('calc_t').setLabel('T').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('calc_clear').setLabel('Clear').setStyle(ButtonStyle.Danger))]}
function emb(e,r){return new EmbedBuilder().setTitle('🧮 Donut SMP Calculator').setDescription(`**Calculation**\n\`${e||'Start building a calculation below.'}\`\n\n**Result**\n### ${r===null?'—':fmt(r)}`).setFooter({text:'TigerBot • Donut SMP Calculator'})}
async function execute(i){const id=i.customId;const cur=i.message.embeds[0]?.description?.match(/\*\*Calculation\*\*\n`([^`]*)`/)?.[1]||'';const a={calc_plus:' + ',calc_minus:' - ',calc_multiply:' × ',calc_divide:' ÷ ',calc_k:'K',calc_m:'M',calc_b:'B',calc_t:'T'};let e=cur==='Start building a calculation below.'?'':cur;if(id==='calc_clear')e='';else e+=a[id]||'';let r=null;try{if(e.trim())r=calc(e)}catch{}await i.update({embeds:[emb(e,r)],components:rows()})}
export default ['calc_plus','calc_minus','calc_multiply','calc_divide','calc_k','calc_m','calc_b','calc_t','calc_clear'].map(name=>({name,execute}));
